### ISSUE TITLE
Связь

### ISSUE THREAD

**Issue by sergkuzn** [SberProcessMining/Sber_Process_Mining#20]
Как можно связаться с администратором репозитория?

**Comment by SberProcessMining** [comment]
The authors' contacts are provided at the bottom of Readme.md, feel free to reach us.

**Comment by sergkuzn** [comment]
No, I need to contact the admin of the repository.

**Comment by sergkuzn** [comment]
@SberProcessMining , please, contact me via the e-mail in my profile or via the one in the README.md file. Or are there any problems (since I haven't been contacted yet)?
