### ISSUE TITLE
Wrong way to compare two types in KMeansSummarizer

### ISSUE THREAD

**Issue by montaglue** [SberProcessMining/Sber_Process_Mining#22]
The problem is in 38 row in https://github.com/SberProcessMining/Sber_Process_Mining/blob/master/sberpm/ml/summarization/_kmsummarizer.py

type(obj) doesn't return string so the comparison is always false

**Comment by SberProcessMining** [comment]
Hello, @montaglue !

Thank you for the feedback we will review changes soon.

**Comment by SberProcessMining** [comment]
Pull request has been merged, thank you!
