### ISSUE TITLE
Cannot import library after 'pip install'

### ISSUE THREAD

**Issue by sashakorekov** [SberProcessMining/Sber_Process_Mining#5]
Platform: windows 10
Installation: pip install sberpm

Error message:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-7a5cfe8cc8b4> in <module>()
----> 1 import sberPM

C:\Users\nosok\Anaconda3\lib\site-packages\sberPM\__init__.py in <module>()
      3 warnings.simplefilter(action='ignore', category=FutureWarning)
      4 
----> 5 from . import bpmn
      6 from . import imitation
      7 from . import metrics

ImportError: cannot import name 'bpmn'

```

**Comment by sashakorekov** [comment]
`C:\Users\nosok\projects>python -m venv sberpm_test_venv

C:\Users\nosok\projects>sberpm_test_venv\Scripts\activate

(sberpm_test_venv) C:\Users\nosok\projects>pip install sberpm
Collecting sberpm
  Downloading https://files.pythonhosted.org/packages/26/5d/91325d9fc4574c72faa8332c00553a9cb5c07b10bc596a76982db2a6a7dc/sberpm-1.0.2.tar.gz (93kB)
    100% |████████████████████████████████| 102kB 1.9MB/s
Collecting numpy<=1.19.3,>=1.18.1 (from sberpm)
  Downloading https://files.pythonhosted.org/packages/c0/d7/fae31ed42256558cad59a13df72ba1312dcb6d303c0f97d918080577be74/numpy-1.19.3-cp36-cp36m-win_amd64.whl (13.2MB)
    100% |████████████████████████████████| 13.3MB 1.5MB/s
Collecting pandas>=1.1.0 (from sberpm)
  Downloading https://files.pythonhosted.org/packages/79/87/8bb36bd4ebae147612c73d1bdc1385db7beebb9eb141c4bfefb33f52c87c/pandas-1.1.5-cp36-cp36m-win_amd64.whl (8.7MB)
    100% |████████████████████████████████| 8.7MB 1.4MB/s
Collecting pydotplus>=2.0.2 (from sberpm)
Collecting graphviz>=0.13.2 (from sberpm)
  Downloading https://files.pythonhosted.org/packages/86/86/89ba50ba65928001d3161f23bfa03945ed18ea13a1d1d44a772ff1fa4e7a/graphviz-0.16-py2.py3-none-any.whl
Collecting scikit-learn>=0.23.2 (from sberpm)
  Downloading https://files.pythonhosted.org/packages/3c/d3/63700971e89bc5024d4356310229f5cdc93927c8c8bf95c53bb7b5e4a62e/scikit_learn-0.24.1-cp36-cp36m-win_amd64.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 1.7MB/s
Collecting python-dateutil>=2.7.3 (from pandas>=1.1.0->sberpm)
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
    100% |████████████████████████████████| 235kB 2.2MB/s
Collecting pytz>=2017.2 (from pandas>=1.1.0->sberpm)
  Downloading https://files.pythonhosted.org/packages/89/06/2c2d3034b4d6bf22f2a4ae546d16925898658a33b4400cfb7e2c1e2871a3/pytz-2020.5-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 1.8MB/s
Collecting pyparsing>=2.0.1 (from pydotplus>=2.0.2->sberpm)
  Downloading https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl (67kB)
    100% |████████████████████████████████| 71kB 1.7MB/s
Collecting scipy>=0.19.1 (from scikit-learn>=0.23.2->sberpm)
  Downloading https://files.pythonhosted.org/packages/f3/9f/80522344838ae24cac9e945240436269cbb92349f7f1f4c9dfc10cb6bad5/scipy-1.5.4-cp36-cp36m-win_amd64.whl (31.2MB)
    100% |████████████████████████████████| 31.2MB 1.5MB/s
Collecting threadpoolctl>=2.0.0 (from scikit-learn>=0.23.2->sberpm)
  Downloading https://files.pythonhosted.org/packages/f7/12/ec3f2e203afa394a149911729357aa48affc59c20e2c1c8297a60f33f133/threadpoolctl-2.1.0-py3-none-any.whl
Collecting joblib>=0.11 (from scikit-learn>=0.23.2->sberpm)
  Downloading https://files.pythonhosted.org/packages/34/5b/bd0f0fb5564183884d8e35b81d06d7ec06a20d1a0c8b4c407f1554691dce/joblib-1.0.0-py3-none-any.whl (302kB)
    100% |████████████████████████████████| 307kB 2.0MB/s
Collecting six>=1.5 (from python-dateutil>=2.7.3->pandas>=1.1.0->sberpm)
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Installing collected packages: numpy, six, python-dateutil, pytz, pandas, pyparsing, pydotplus, graphviz, scipy, threadpoolctl, joblib, scikit-learn, sberpm
  Running setup.py install for sberpm ... done
Successfully installed graphviz-0.16 joblib-1.0.0 numpy-1.19.3 pandas-1.1.5 pydotplus-2.0.2 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2020.5 sberpm-1.0.2 scikit-learn-0.24.1 scipy-1.5.4 six-1.15.0 threadpoolctl-2.1.0
You are using pip version 9.0.3, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

**Comment by sashakorekov** [comment]
![image](https://user-images.githubusercontent.com/28607569/105171385-370b2580-5b2f-11eb-863f-1e2168332110.png)

**Comment by SberProcessMining** [comment]
Hello!

It is strange that the library is installed in the sberpm_test_venv environment, but then it is imported from the C:\Users\nosok\Anaconda3\lib\site-packages directory, but not from the sberpm_test_venv directory.

Perhaps you should add a kernel to Jupyter and select it when running the code. The following code might help:
pip install ipykernel
python -m ipykernel install --user --name=sberpm_test_venv

**Comment by sashakorekov** [comment]
Yep, manual kernel switching helped, thanks.
